# Generated by Django 5.0.7 on 2024-08-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='risk_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='turnover_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
